name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      -
        name: set env
        run: |
          touch ./auth-service/src/main/resources/application.properties
          echo "${{secrets.APPLICATION_YML}}" > ./auth-service/src/main/resources/application.properties
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: set tag
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: jusuk/auth-server
          tag-semver: latest
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPONAME}}:latest
      -
        name: Docker push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPONAME}}:latest
        # uses: docker/build-push-action@v2
        # with:
        #   context: .
        #   file: ./Dockerfile
        #   platforms: linux/amd64
        #   push: true
        #   tags: ${{ steps.docker_meta.outputs.tags }}
        #   labels: ${{ steps.docker_meta.outputs.labels }}
